version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=${TODOS_USER}
      - POSTGRES_PASSWORD=${TODOS_PASSWORD}
      - POSTGRES_DB=todos
    ports:
      - '5433:5432'

  api:
    image: todos-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todos
      - POSTGRES_USER=${TODOS_USER}
      - POSTGRES_PASSWORD=${TODOS_PASSWORD}
      - JAVA_OPTS=-Xms50M -Xmx100M
    depends_on:
      - db
    ports:
      - '8080:8080'

  ui:
    image: todos-ui
    environment:
#      - VUE_APP_BACKEND_URL=http://localhost:8080/api/
      - PORT=8081
    depends_on:
      - api
    ports:
      - '8081:8081'
